spring.application.name=Manager

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver

# TODO: change create to validate or none when done
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=flying_spaghetti_monster
jwt.subject=user_details
jwt.issuer=Manager_Web_App
jwt.expiration_period_minutes=60

cors.url=${MYAPP_CORS_URL}

yookassa.shopId=${MYSHOP_ID}
yookassa.secretKey=${MYSHOP_SECRET_KEY}

yookassa.returnUrl=https://${MYAPP_URL}/api/payments/callback

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=my_app_email@gmail.com
spring.mail.password=my_app_password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true